name: Build Status

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt -U
        pip install -U pytest pytest-cov flake8 pylint codecov
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make test
    - name: Codecov
      run: |
        codecov --token 3e049fa4-4e8d-4368-b805-bb3f40603420
